# Generated by Django 4.0.3 on 2022-03-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lmsItem',
            fields=[
                ('lms_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('lms_pw', models.CharField(max_length=30)),
            ],
        ),
    ]
